apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      tag: udacitypython
  template:
    metadata:
      labels:
        tag: udacitypython
    spec:
      containers:
      - name: flaskapp
        image: ayamorsi/udacity
